name: Build Raspberry Pi OS Lite Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm, linux/arm64

      - name: Build Raspberry Pi OS Lite Image
        run: |
          # Download Raspberry Pi OS Lite image (replace with the actual URL)
          wget --no-verbose https://downloads.raspberrypi.org/raspios_lite_arm64_latest -O raspbian-lite.xz
          xz --decompress raspbian-lite.xz
          ls

          # Mount the image
          mkdir -p mount-point
          sudo mount -o loop,offset=268435456 raspbian-lite.img mount-point

          # Copy your custom code to the image (replace src and dest paths)
          cp -r ./* mount-point/

          # Unmount the image
          sudo umount mount-point
        shell: bash

      - name: Save Modified Image
        run: mv raspbian-lite.img modified-raspbian-lite.img

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: custom-raspbian-image
          path: modified-raspbian-lite.img
